[tool.poetry]
name = "splink_graph"
version = "0.2.1"
description = "a small set of graph functions"
authors = ["Theodore Manassis <theodore.manassis@digital.justice.gov.uk>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pyspark = "2.4"
networkx = "^2.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
